### ISSUE TITLE
Highway man can walk into Betty's shop

### ISSUE THREAD

**Issue by NotSinan** [NotSinan/DreamBotQuester#26]
The highway man can traverse into Betty's shop when it is aggressive to the local player. If the highway man gets stuck there, it will continually attack lower level accounts.

Suggestions for fix:
- Hop world.

**Comment by Dreambotter420** [comment]
added EnableRunDuringCombatLeaf that enables run during combat and added logic inside RetrieveEyeOfNewtLeaf that hops upon highwayman inside the shop if combat lvl is <=10 (<= 2x the aggressive mob's lvl)
