### ISSUE TITLE
walkToArea method seems really buggy.

### ISSUE THREAD

**Issue by NotSinan** [NotSinan/DreamBotQuester#64]
I think using getSleepDelay messes with tick timeout in a way that bugs the ticks out. Probably should change the implementation so that walking is less robotic and more efficient.

**Comment by Dreambotter420** [comment]
In latest commit, I removed all references to Walking.shouldWalk in favor of Timing.loopReturn delayed walk actions. Walking should now be only delayed according to Tick Timeout and the standard Walking.walk() API call when handling Objects (a single walk() call to handle an obstacle may not return until multiple attempts at it and succesfully walking to it)
